### ISSUE TITLE
Results funcid

### ISSUE THREAD

**Issue by nessusmonkey** [iotcube/hmark#1]
Hi,
Can you help me please to determine how can I identify the affected line of a vuln clone based on the JSON array? It contains a key-value  like "funcid":"6"}, how is that referenced to the affected line?

The source tree does not highlight the affected code section, just the generic CVE info for the given vuln and the sample patch diff.

Thanks

**Comment by squizz617** [comment]
Hi nessusmonkey,

Unfortunately, we cannot provide you with direct references to the line numbers because we don't have the information either. In the JSON array, what you see is everything we collect from the users as inputs. This is our design choice not to force users expose any sensitive information of their source code.

So, you'd have to infer the affected lines through "funcid" which refers to the numeric order of a function. For example if you found a pair like "funcid": "6", then that function is the sixth function in the file.

By the way, I don't really agree that the source tree does not highlight the affected code section. The given patches are recommendation patches which could be applied to resolve the detected vulnerability, which in other words mean that you can look for the lines that the given patch removes (prefixed by "-" signs) in your own code to find the affected lines. By this you can conveniently identify the problematic portion in your source code not even using the funcid attribute.

Thanks,
-Seulbae

**Comment by nessusmonkey** [comment]
Excellent, thanks
